### ISSUE TITLE
file.writeAsBytes in getModelPath produce (OS Error: Is a directory, errno = 21) error.

### ISSUE THREAD

**Issue by ChurikiTenna** [flutter-ml/google_ml_kit_flutter#523]
**Describe the bug**

I followed [this](https://pub.dev/packages/google_mlkit_image_labeling) to use my custom tflite in flutter.
However, on writeAsBytes, it produce error below.

```
TFLite.failed: FileSystemException: Cannot open file, path = '/var/mobile/Containers/Data/Application/CB720111-3448-4F85-AE26-2122D8EC273C/Library/Application Support/lib/images/OUTPUT-MODEL.tflite' (OS Error: Is a directory, errno = 21)
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: Cannot open file, path = '/var/mobile/Containers/Data/Application/CB720111-3448-4F85-AE26-2122D8EC273C/Library/Application Support/lib/images/OUTPUT-MODEL.tflite' (OS Error: Is a directory, errno = 21)
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
<asynchronous suspension>
#2      _MenstrualCupCameraState.getModelPath (package:integro/pages/subs/menstrual_cup_camera.dart:265:7)
<asynchronous suspension>
#3      _MenstrualCupCameraState.initialize (package:integro/pages/subs/menstrual_cup_camera.dart:60:25)
<asynchronous suspension>
```

**To Reproduce**

Run code below.

```

initialize() {
try {
      final modelPath = await getModelPath('lib/images/OUTPUT-MODEL.tflite');
      final options = LocalLabelerOptions(
          confidenceThreshold: 0.4, modelPath: modelPath //model!.file.path
          );
    } catch (exception) {
      print('TFLite.failed: $exception');
      rethrow;
    }
}
Future<String> getModelPath(String asset) async {
    final path = '${(await getApplicationSupportDirectory()).path}/$asset';
    await Directory(dirname(path)).create(recursive: true);
    print("getModelPath.d ${dirname(path)}");
    final file = File(path);
    print("getModelPath.f $file");
    if (!await file.exists()) {
      print("does not exists");
      final byteData = await rootBundle.load(asset);
      print("did.load");
      await file.writeAsBytes(byteData.buffer
          .asUint8List(byteData.offsetInBytes, byteData.lengthInBytes));
      print("did.writeAsBytes");
    }
    return file.path;
  }
```

**Expected behavior**
Load tflile.

**Platform (please complete the following information):**
 - OS: iOS
 - Device: iPhone 11
 - OS: 16.6
 - Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git
- Plugin version

**Comment by ChurikiTenna** [comment]
changing the file location in assets folder and renaming path to `getModelPath('assets/OUTPUT-MODEL.tflite');` worked.
