### ISSUE TITLE
 Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.cargoguard.app/com.cargoguard.app.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=3548984, result=-1, data=Intent { (has extras) }} to activity {com.cargoguard.app/com.cargoguard.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 

### ISSUE THREAD

**Issue by sadaqatdev** [flutter-ml/google_ml_kit_flutter#719]
### Describe your issue. If applicable, add screenshots to help explain your problem.

          Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.cargoguard.app/com.cargoguard.app.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=3548984, result=-1, data=Intent { (has extras) }} to activity {com.cargoguard.app/com.cargoguard.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void t8.k$d.a(java.lang.Object)' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5378)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5444)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
        

### Steps to reproduce.

use heavy image , large image

### What is the expected result?

path of scan image

### Did you try our example app?

Yes

### Is it reproducible in the example app?

Yes

### Reproducible in which OS?

Android

### Flutter/Dart Version?

[✓] Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
[✓] VS Code (version 1.95.2)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for Naeem's iPhone. Ensure the device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

### Plugin Version?

 google_mlkit_document_scanner: 0.3.0

**Comment by sadaqatdev** [comment]
Caused by java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=3548984, result=-1, data=Intent { (has extras) }} to activity {com.cargoguard.app/com.cargoguard.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void t8.k$d.a(java.lang.Object)' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5994)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5348)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5444)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by sadaqatdev** [comment]
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void t8.k$d.a(java.lang.Object)' on a null object reference
       at com.google_mlkit_document_scanner.DocumentScanner.handleScanningResult(DocumentScanner.java:1)
       at com.google_mlkit_document_scanner.DocumentScanner.onActivityResult(DocumentScanner.java:1)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:1)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:1)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:1)
       at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:10)
       at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:5)
       at android.app.Activity.dispatchActivityResult(Activity.java:8951)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5987)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5348)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5444)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by sadaqatdev** [comment]
@fbernaly when this issue will address

**Comment by fbernaly** [comment]
I do not have an ETA. Feel free to fork the repo and send a PR with your contribution. Contributions are always welcome.
